name: CI/CD Pipeline

# 触发条件：推送到main分支或创建Pull Request时
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# 定义作业
jobs:
  # 构建和测试作业
  build-and-test:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 服务配置
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sky_take_out
          MYSQL_USER: sky
          MYSQL_PASSWORD: sky123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    # 步骤
    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 2. 设置Java环境
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    # 3. 缓存Maven依赖
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # 4. 构建项目
    - name: Build with Maven
      run: mvn clean compile -B
      
    # 5. 等待数据库启动
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P3306 -uroot -proot --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done
        echo "MySQL is ready!"
        
    # 6. 运行测试
    - name: Run tests
      run: mvn test -B -Dspring.profiles.active=test
      
    # 7. 生成测试报告
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        
    # 8. 打包项目
    - name: Package application
      run: mvn package -DskipTests -B
      
    # 9. 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sky-take-out-jar
        path: sky-server/target/*.jar
